### PR TITLE
Improve the share map panel

### PR DESCRIPTION
**Pull request by gpetit**
Dear MViewer team, here is a proposition of optimisation for the "Share map" panel.

Here are the modifications :
- Centering the title and changing from H5 to H4
- Removing "Georchestra" references to be more generic
- Replacing the "Lien vers la carte" link by a clickable icon

Thanks for your great work.

### CODE REVIEW

**Comment by spelhate** [comment]
Hi  Gwendall,
Many thanks for your interest in mviewer project and your first pull request.
 I'am ok with your proposal except "Removing "Georchestra" references to be more generic".
In fact, this functionnality is not generic but specific to georchestra platforms. This action is a way to send on a GeorChestra viewer all the visible layers present in the active mviewer.
Perhaps it's possible to set this functionnality optional with a new parameter in config.xml if you don't want this share functionnality ?

**Comment by gpetit** [comment]
Thanks @spelhate for your response.
I'm probably wrong, but I thought Mviewer should be an independent/generic project, in order to be reused by another oragisms.
As you mentionned, this functionnality is specific to your needs, but not ours ;-)

To be more simple (and trying to be generic), maybe you could extract this part of code (Share map bloc) in an external .html file as you already done with mviewer_help.html ? This way, users are free to adapt this file without modifying index.html ?

Just for your information, @ebocher and I are working on this website : http://mapuce.orbisgis.org/ which is based on MViewer. Here, the "share map" panel is already adapted to our need

Finally, note that if you reject my PR (because of Georchestra issue), I'm afraid my proposition will be bad because the UI won't be nice (or we will have to add 3 columns : 1 for link, 1 for Georchestra and 1 for QR code ?)

**Comment by spelhate** [comment]
@gpetit, i will accept your PR and add this specific functionnality with extra config.

**Comment by gpetit** [comment]
Thanks

**Pull request merged**
