### PR TITLE
Load layer indexed with Fuse only once (fix #59)

### LINKED ISSUE #59: Fuse: only load layer source once
With the current version of mviewer, when a layer is indexed with Fuse the data source is loaded twice :
- once by the fuse indexation
- once by OpenLayers itself

@spelhate asked if it is possible to load the data source only once (see https://github.com/geobretagne/mviewer/pull/57#issuecomment-346796767).

This would be nice : it would be cleaner and it would probably enable the use of Fuse with other kinds of vector layers.

The idea would be to use the features loaded by OpenLayers layer source in the fuse indexation function instead of requesting the data source with another ajax request.

The indexation process occurs in the _processLayer function. It seems that this function is called before the data is fully loaded by OpenLayers.

In order to load the data source only once we would probably need to observe some kind of events of the layer. We would index the layer when some kind of "end of load" event is received. I don't know yet if it's possible/easy to do this with OpenLayers.

### PR DESCRIPTION
**Pull request by bchartier**
This fix has only been tested on a geojson layer and a custom layer loading a geojson file.
The process of the searchable property of the layer has moved just after _map.addLayer allowing access to the features of layer. I hope this don't break the process of layers indexed with Elasticsearch.

### CODE REVIEW

**Comment by spelhate** [comment]
> The process of the searchable property of the layer has moved just after _map.addLayer allowing access to the features of layer

Why have you move this portion of code ? I have tested your dev without move and it works as well.

**Comment by bchartier** [comment]
I moved this portion of code the features of the layer on which I ran my tests were not yet accessible. They became accessible only when the layer was added to the map. I may have done my tests the wrong way. I will do some more tests. If you are right, I will put this portion of code to its initial place.

**Comment by spelhate** [comment]
Yes i am right !

**Comment by bchartier** [comment]
For every kind of layers?

**Comment by spelhate** [comment]
What do you mean by 

> kind of layers?

**Comment by bchartier** [comment]
I've only tested GeoJSON layers and GeoJSON files loaded from a custom layer. I haven't tested other kinds of vector layers (WFS for example). I don't know if the behaviour I encountered may be different with other kinds of layers.
The behaviour I encountered was identical with data loaded in an OpeLayers demo example and with mviewer: vector features were accessible only after a map.addLayer.
I will run some more tests.

**Comment by bchartier** [comment]
You are right. I don't understand what misled me during my initial tests. I probably changed something in the indexation part but I can't figure out what.

I put back the indexation code portion at its initial place. This pull request is probably ready for a merge.

**Comment by spelhate** [comment]
Merci @bchartier .

**Pull request merged**
