### PR TITLE
[GetFeatureInfo] Add key_value and serialized access to feature fields...

### PR DESCRIPTION
**Pull request by jeanpommier**
...in the mustache templates, allowing to iterate through the fields without the need to know the keys values or hardcode them, e.g.
```
<script>
	{{#fields_kv}}
		console.log("{{key}}: {{value}}")
	{{/fields_kv}}

	console.log("{{serialized}}")
</script>
```
fields_kv and serialized attributes are [function generators](https://github.com/janl/mustache.js#functions), so it doesn't consume resources while you don't use them

Solves #205

### CODE REVIEW

**Comment by Gaetanbrl** [comment]
Have you a public demo ?

**Comment by Gaetanbrl** [comment]
> fields_kv and serialized attributes are function generators

Thanks for this usefull tips.

**Comment by Gaetanbrl** [comment]
@jeanpommier i get you branch from pi-geosolution/mviewer repository.

To test this PRnow , i try to display `key : value` as HTML list. I had insert this code after `</li>` line.
https://github.com/geobretagne/mviewer/blob/3d21b02c2390e8c25f85412d3db02f5beb51c072/templates/global.lycee.mst#L18

This is my code : 
```
	</li>
	<div>
		<h3>Clés/valeurs</h3>
		<ul class="item" style="width:238px;">
		{{#fields_kv}}
			<li>{{key}} : {{value}}</li>
		{{/fields_kv}}
		</ul>
	</div>
{{/features}}
```

Maybe i'm wrong, but i can't display this part of template for the first clicked item. 
It's the same behavior if i click on only one object.

image

**Comment by Gaetanbrl** [comment]
My bad, i need to move `{{#fields_kv}}` code inside `<li></li>`.

**Comment by jeanpommier** [comment]
Ah ? It seemed nice as you did it.
Your picture make me realize I didn't filter out the serialized data from the field_kv array, which would be better (you might want key-value access or serialized, but rarely both)

Sorry, no, I don't have live demo right now.

**Comment by Gaetanbrl** [comment]
> Your picture make me realize I didn't filter out the serialized data from the field_kv array

Indeed, that could be better and more 😉 :)

**Comment by Gaetanbrl** [comment]
So, if you have this code, it works : 
```
{{#features}}
	<li class="item" style="width:238px;">
		...
			<ul>
				{{#fields_kv}}
					<li>{{key}} : {{value}}</li>
				{{/fields_kv}}
			</ul>
		...
	</li>
{{/features}}
```

... Don't know why but my specific case don't work with this code and only for each first or alone items:
```
{{#features}}
	<li class="item" style="width:238px;">
		...	
	</li>
	<li>
		<ul>
			{{#fields_kv}}
				<li>{{key}} : {{value}}</li>
			{{/fields_kv}}
		</ul>
	</li>	
{{/features}}
```

**Comment by jeanpommier** [comment]
This seems weird, but I don't think it can be related to this PR's code. I'm just adding 2 more tags...

**Comment by Gaetanbrl** [comment]
> This seems weird, but I don't think it can be related to this PR's code.

I think this behavior already exist before... but i need to be test with geobretagne/mviewer/master version to be sur.

**Comment by jeanpommier** [comment]
> > Your picture make me realize I didn't filter out the serialized data from the field_kv array
> 
> Indeed, that could be better and more readable wink.

done

**Comment by Gaetanbrl** [comment]
> I think this behavior already exist before... but i need to be test with geobretagne/mviewer/master version to be sur.

Tested and already present in geobretagne/mviewer/master. Tested with [templates/global.lycee.mst](https://github.com/geobretagne/mviewer/blob/master/templates/global.lycee.mst).

**Comment by spelhate** [comment]
> My bad, i need to move `{{#fields_kv}}` code inside first main `<li></li>`.

Li returned by template must have **item** class like this : `<li class="item">...</li>`
It's in the doc https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_tpl.html

**Comment by spelhate** [comment]
Could you target the develop branch rather than master with the PR. Thank's.

**Comment by jeanpommier** [comment]
@spelhate  OK, done. It doesn't seems to change anything. Does it mean it won't be merged into master any time soon ?

**Comment by spelhate** [comment]
PR is ok for me. We target develop branch because we use git  workflow as explained here.

**Comment by Gaetanbrl** [comment]
> PR is ok for me. We target develop branch because we use git workflow as explained here.

[here](https://mviewerdoc.readthedocs.io/fr/latest/doc_contrib/git.html#presentation-git-flow)  🤠

**Pull request merged**
