### PR TITLE
Fixes some minor typo in the documentation

### PR DESCRIPTION
**Pull request by pblottiere**

### CODE REVIEW

**Comment by spelhate** [comment]
Like #345 , can ou target develop branch for this PR. Thank's.

**Comment by pblottiere** [comment]
> can ou target develop branch for this PR. Thank's.

Done.

**Comment by Gaetanbrl** [comment]
Thanks for this great review @pblottiere  ! @spelhate i merge it.

**Comment by pblottiere** [comment]
Honestly, I'm very impressed with the documentation of Mviewer. Big :+1:

**Comment by Gaetanbrl** [comment]
That's why all contributions are precious 👍

**Pull request merged**
