### PR TITLE
Fix CI by splitting github workflow

### PR DESCRIPTION
**Pull request by RemiDesgrange**

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Up for a review ? Thanks.

**Comment by bchartier** [comment]
I will have a look at it this week.

**Review by bchartier — CHANGES_REQUESTED** [review]
This PR is OK for me.
I think we could have managed the build of docker images for commits and releases in the same file like we did for GeoContrib (see https://github.com/neogeo-technologies/geocontrib/blob/develop/.github/workflows/geocontrib.yml) by using tests on github.ref and github.event_name. But htat's OK.
Just a small request: can you rename both files located in .github/workflows in order to make obvious what each file is for? (one for building the docker images after commit events and one for building images after release events)

**Comment by fvanderbiest** [comment]
In addition, workflow names can be overriden with the `name` key in the yaml file, (see eg https://github.com/georchestra/georchestra/blob/master/.github/workflows/sp.yml#L1) - probably a good idea to put something relevant in here.

**Review by bchartier — APPROVED** [review]

**Comment by bchartier** [comment]
Thank you!

**Pull request merged**
